name: "ACoC SAST Incremental"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: cwtravis/asoc_sast_incremental
          path: tools
      - name: Change Working Dir
        run: 
          cd main & python3 ../tools/SAST_Incremental.py ${{secrets.ASOC_KEY}} ${{secrets.ASOC_SECRET}} ${{secrets.APP_ID}}
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.6
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{secrets.APP_ID}}
