name: "ACoC SAST Incremental"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          branch: 'master'
          owner: 'cwtravis'
          repository: 'demos'
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: cwtravis/asoc_sast_incremental
          path: tools
      - name: Generate ASoC Config XML
        run: 
          python3 ${GITHUB_WORKSPACE}/tools/SAST_Incremental.py ${{secrets.ASOC_KEY}} ${{secrets.ASOC_SECRET}} ${{secrets.APP_ID}}
      - name: Remove Incremental Tooling
        run: 
          rm -rf tools
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.6
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{secrets.APP_ID}}
